### ISSUE TITLE
When calling EncryptInDomain() ensure the domain is valid for encryption

### ISSUE THREAD

**Issue by interstellarPotato** [peacemakr-io/peacemakr-go-sdk#57]
If a use domain in not valid for encryption, do not select an alternative domain - fail with appropriate message.

repo: have a least one use domain (domain X) valid for encryption. Use an invalid domain (domain Y with expired ttl on encrypt) when calling the function encryptInDomain(). domain X will be picked. 

Desired behaviour: fail to encrypt + a message why.

**Comment by notasecret** [comment]
Thx @interstellarPotato . 

I would only add that in the go-sdk, it should fail the encryption call, and return an err that explains why it failed, but, on the peacemakr-cli, it should result in an error message, something like "[name of requested domain] is not valid for encryption due to X", where X could be (a) it doesn't exist, (b) the ttl is expired for encryption, or whatnot
